-- Role: rezepte
-- DROP ROLE rezepte;

CREATE ROLE rezepte WITH
  LOGIN
  NOSUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION
  ENCRYPTED PASSWORD 'md557bb7f2a4c1f1fcd1495acc2647ef626';